[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = true
include = '\.py$'
exclude = '''
/(
    \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["transform", "agent", "webapp"]
skip = [".venv"]